name: Publish Report

on: [push]
  
jobs:
  create_pdf:
    runs-on: ubuntu-latest
    container:
      image: blang/latex
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Create PDF
        run: pdflatex report_setores/main.tex 

  # setup_gcloud:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - id: 'auth'
  #     uses: 'google-github-actions/auth@v0'
  #     with:
  #       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

  #   - name: 'Set up Cloud SDK'
  #     uses: 'google-github-actions/setup-gcloud@v0'

  # upload_report:
  #   runs-on: ubuntu-latest
  #   steps:
  #     run: gsutil cp report_setores/report_setores.pdf gs:://pacto-equidade/pacto_public